---
- name: restart ebpf-tcp-exporter
  systemd:
    daemon_reload: yes
    name: ebpf-tcp-exporter
    state: restarted
  become: true

- name: restart ebpf-execsnoop
  systemd:
    daemon_reload: yes
    name: ebpf-execsnoop
    state: restarted
  become: true

- name: restart ebpf-opensnoop
  systemd:
    daemon_reload: yes
    name: ebpf-opensnoop
    state: restarted
  become: true